import Foundation

// MARK: - AI Service Errors

/// Errors that can occur during AI API operations.
enum AIServiceError: Error, LocalizedError {
    case noAPIKey
    case invalidEndpoint
    case requestFailed(String)
    case timeout
    case invalidResponse(String)
    case parsingFailed(String)
    case networkError(Error)

    var errorDescription: String? {
        switch self {
        case .noAPIKey:
            return "No API key configured. Please set your AI API key in Settings."
        case .invalidEndpoint:
            return "Invalid AI endpoint URL. Please check your settings."
        case .requestFailed(let reason):
            return "AI request failed: \(reason)"
        case .timeout:
            return "AI request timed out. Please try again or increase the timeout in Settings."
        case .invalidResponse(let detail):
            return "Invalid response from AI: \(detail)"
        case .parsingFailed(let detail):
            return "Failed to parse AI response: \(detail)"
        case .networkError(let error):
            return "Network error: \(error.localizedDescription)"
        }
    }
}

// MARK: - Generated Ticket

/// Represents a ticket generated by AI from PRD analysis.
struct GeneratedTicket: Identifiable, Equatable, Sendable {
    let id: UUID
    var title: String
    var description: String
    var priority: TicketPriority
    var estimatedStoryPoints: Int
    var skillClassification: SkillProfile
    var suggestedDependencies: [String]

    init(
        id: UUID = UUID(),
        title: String,
        description: String,
        priority: TicketPriority = .medium,
        estimatedStoryPoints: Int = 3,
        skillClassification: SkillProfile = .fullstack,
        suggestedDependencies: [String] = []
    ) {
        self.id = id
        self.title = title
        self.description = description
        self.priority = priority
        self.estimatedStoryPoints = estimatedStoryPoints
        self.skillClassification = skillClassification
        self.suggestedDependencies = suggestedDependencies
    }

    static func == (lhs: GeneratedTicket, rhs: GeneratedTicket) -> Bool {
        lhs.id == rhs.id &&
        lhs.title == rhs.title &&
        lhs.description == rhs.description &&
        lhs.priority == rhs.priority &&
        lhs.estimatedStoryPoints == rhs.estimatedStoryPoints &&
        lhs.skillClassification == rhs.skillClassification &&
        lhs.suggestedDependencies == rhs.suggestedDependencies
    }
}

// MARK: - Re-Evaluation Result

/// Result of comparing an updated PRD against existing tickets.
struct ReEvaluationResult: Sendable {
    var newTickets: [GeneratedTicket]
    var changedTickets: [(existingTitle: String, suggested: GeneratedTicket)]
    var removedTicketTitles: [String]
    var unchangedTicketTitles: [String]
}

// MARK: - AI API Response Models

/// OpenAI-compatible chat completion response.
struct AIChatCompletionResponse: Codable {
    let id: String?
    let choices: [AIChoice]

    struct AIChoice: Codable {
        let message: AIMessage
        let finishReason: String?

        enum CodingKeys: String, CodingKey {
            case message
            case finishReason = "finish_reason"
        }
    }

    struct AIMessage: Codable {
        let role: String
        let content: String?
    }
}

/// JSON structure expected from AI for ticket breakdown.
struct AITicketBreakdownResponse: Codable {
    let tickets: [AITicketItem]

    struct AITicketItem: Codable {
        let title: String
        let description: String
        let priority: String
        let storyPoints: Int
        let skillClassification: String
        let dependencies: [String]?

        enum CodingKeys: String, CodingKey {
            case title
            case description
            case priority
            case storyPoints = "story_points"
            case skillClassification = "skill_classification"
            case dependencies
        }
    }
}

/// JSON structure expected from AI for re-evaluation.
struct AIReEvaluationResponse: Codable {
    let newTickets: [AITicketBreakdownResponse.AITicketItem]
    let changedTickets: [AIChangedTicketItem]
    let removedTickets: [String]
    let unchangedTickets: [String]

    enum CodingKeys: String, CodingKey {
        case newTickets = "new_tickets"
        case changedTickets = "changed_tickets"
        case removedTickets = "removed_tickets"
        case unchangedTickets = "unchanged_tickets"
    }

    struct AIChangedTicketItem: Codable {
        let existingTitle: String
        let suggested: AITicketBreakdownResponse.AITicketItem

        enum CodingKeys: String, CodingKey {
            case existingTitle = "existing_title"
            case suggested
        }
    }
}

// MARK: - AIService

/// Actor-based service for AI-powered PRD breakdown and re-evaluation.
///
/// Communicates with an OpenAI-compatible API (OpenRouter or direct) to analyze
/// PRD documents and generate structured ticket breakdowns.
actor AIService {

    // MARK: - Properties

    /// The AI API endpoint URL.
    private var endpoint: URL

    /// The request timeout in seconds.
    private var timeout: TimeInterval

    /// The encryption service for secure API key storage.
    private let encryptionService: EncryptionService

    /// The Keychain key used to store the AI API key.
    private static let apiKeyKeychainKey = "ai-api-key"

    /// The URLSession used for requests.
    private let session: URLSession

    // MARK: - Initialization

    /// Creates an AIService with the specified configuration.
    /// - Parameters:
    ///   - endpoint: The AI API endpoint URL (OpenAI-compatible).
    ///   - timeout: Request timeout in seconds (default: 120s).
    ///   - encryptionService: The encryption service for API key storage.
    ///   - session: Optional URLSession for testing (default: shared).
    init(
        endpoint: URL = URL(string: "https://openrouter.ai/api/v1")!,
        timeout: TimeInterval = AppConstants.defaultAITimeout,
        encryptionService: EncryptionService,
        session: URLSession? = nil
    ) {
        self.endpoint = endpoint
        self.timeout = timeout
        self.encryptionService = encryptionService

        if let session = session {
            self.session = session
        } else {
            let config = URLSessionConfiguration.default
            config.timeoutIntervalForRequest = timeout
            config.timeoutIntervalForResource = timeout
            self.session = URLSession(configuration: config)
        }
    }

    // MARK: - Configuration

    /// Updates the AI endpoint URL.
    func setEndpoint(_ url: URL) {
        self.endpoint = url
    }

    /// Updates the request timeout.
    func setTimeout(_ seconds: TimeInterval) {
        self.timeout = seconds
    }

    /// Gets the current endpoint URL.
    func getEndpoint() -> URL {
        return endpoint
    }

    /// Gets the current timeout.
    func getTimeout() -> TimeInterval {
        return timeout
    }

    // MARK: - API Key Management

    /// Stores the AI API key securely via EncryptionService.
    /// - Parameter apiKey: The API key to store.
    func storeAPIKey(_ apiKey: String) throws {
        try encryptionService.storeInKeychain(key: Self.apiKeyKeychainKey, value: apiKey)
    }

    /// Retrieves the stored AI API key.
    /// - Returns: The API key, or nil if not stored.
    func retrieveAPIKey() -> String? {
        try? encryptionService.retrieveFromKeychain(key: Self.apiKeyKeychainKey)
    }

    /// Deletes the stored AI API key.
    func deleteAPIKey() throws {
        try encryptionService.deleteFromKeychain(key: Self.apiKeyKeychainKey)
    }

    /// Returns the masked API key for display.
    func maskedAPIKey() -> String {
        guard let key = retrieveAPIKey() else { return "" }
        return encryptionService.maskToken(key)
    }

    // MARK: - PRD Breakdown

    /// Breaks down a PRD document into structured tickets using AI.
    /// - Parameter content: The PRD document content.
    /// - Returns: An array of generated tickets.
    /// - Throws: `AIServiceError` if the operation fails.
    func breakdownPRD(content: String) async throws -> [GeneratedTicket] {
        let apiKey = try getAPIKeyOrThrow()

        let systemPrompt = """
        You are a technical project manager. Analyze the following PRD (Product Requirements Document) \
        and break it down into actionable development tickets.

        For each ticket, provide:
        - title: A concise, actionable title
        - description: Detailed description of what needs to be implemented
        - priority: One of "critical", "high", "medium", "low"
        - story_points: Fibonacci number (1, 2, 3, 5, 8, 13, 21) estimating effort
        - skill_classification: One of "beHeavy" (backend), "feHeavy" (frontend), "fullstack"
        - dependencies: Array of other ticket titles this depends on (can be empty)

        Respond ONLY with valid JSON in this exact format:
        {
          "tickets": [
            {
              "title": "...",
              "description": "...",
              "priority": "...",
              "story_points": 3,
              "skill_classification": "...",
              "dependencies": ["..."]
            }
          ]
        }
        """

        let response = try await sendChatRequest(
            systemPrompt: systemPrompt,
            userMessage: content,
            apiKey: apiKey
        )

        return try parseBreakdownResponse(response)
    }

    // MARK: - Re-Evaluation

    /// Re-evaluates an updated PRD against existing tickets.
    /// - Parameters:
    ///   - updatedPRD: The updated PRD content.
    ///   - existingTicketTitles: Titles of existing tickets for comparison.
    /// - Returns: A `ReEvaluationResult` showing new, changed, removed, and unchanged tickets.
    /// - Throws: `AIServiceError` if the operation fails.
    func reEvaluate(updatedPRD: String, existingTicketTitles: [String]) async throws -> ReEvaluationResult {
        let apiKey = try getAPIKeyOrThrow()

        let existingList = existingTicketTitles.map { "- \($0)" }.joined(separator: "\n")

        let systemPrompt = """
        You are a technical project manager. Compare the updated PRD with the existing tickets \
        and determine what has changed.

        Existing tickets:
        \(existingList)

        Analyze the updated PRD and categorize changes into:
        - new_tickets: Tickets that need to be created (not covered by existing)
        - changed_tickets: Existing tickets that need updates based on PRD changes
        - removed_tickets: Existing ticket titles no longer needed
        - unchanged_tickets: Existing ticket titles still valid as-is

        For new and changed tickets, provide full ticket details.

        Respond ONLY with valid JSON in this exact format:
        {
          "new_tickets": [
            {
              "title": "...",
              "description": "...",
              "priority": "...",
              "story_points": 3,
              "skill_classification": "...",
              "dependencies": ["..."]
            }
          ],
          "changed_tickets": [
            {
              "existing_title": "...",
              "suggested": {
                "title": "...",
                "description": "...",
                "priority": "...",
                "story_points": 3,
                "skill_classification": "...",
                "dependencies": ["..."]
              }
            }
          ],
          "removed_tickets": ["..."],
          "unchanged_tickets": ["..."]
        }
        """

        let response = try await sendChatRequest(
            systemPrompt: systemPrompt,
            userMessage: updatedPRD,
            apiKey: apiKey
        )

        return try parseReEvaluationResponse(response)
    }

    // MARK: - Private Helpers

    /// Retrieves the API key or throws if not configured.
    private func getAPIKeyOrThrow() throws -> String {
        guard let apiKey = retrieveAPIKey(), !apiKey.isEmpty else {
            throw AIServiceError.noAPIKey
        }
        return apiKey
    }

    /// Sends a chat completion request to the OpenAI-compatible API.
    private func sendChatRequest(systemPrompt: String, userMessage: String, apiKey: String) async throws -> String {
        let chatEndpoint = endpoint.appendingPathComponent("chat/completions")

        var request = URLRequest(url: chatEndpoint)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue("Bearer \(apiKey)", forHTTPHeaderField: "Authorization")
        request.timeoutInterval = timeout

        let body: [String: Any] = [
            "model": "gpt-4",
            "messages": [
                ["role": "system", "content": systemPrompt],
                ["role": "user", "content": userMessage]
            ],
            "temperature": 0.3,
            "max_tokens": 4096
        ]

        request.httpBody = try JSONSerialization.data(withJSONObject: body)

        let data: Data
        let response: URLResponse

        do {
            (data, response) = try await session.data(for: request)
        } catch let error as URLError where error.code == .timedOut {
            throw AIServiceError.timeout
        } catch {
            throw AIServiceError.networkError(error)
        }

        guard let httpResponse = response as? HTTPURLResponse else {
            throw AIServiceError.invalidResponse("Not an HTTP response")
        }

        guard (200...299).contains(httpResponse.statusCode) else {
            let errorBody = String(data: data, encoding: .utf8) ?? "Unknown error"
            throw AIServiceError.requestFailed("HTTP \(httpResponse.statusCode): \(errorBody)")
        }

        let chatResponse = try JSONDecoder().decode(AIChatCompletionResponse.self, from: data)

        guard let content = chatResponse.choices.first?.message.content else {
            throw AIServiceError.invalidResponse("No content in AI response")
        }

        return content
    }

    // MARK: - Response Parsing

    /// Parses the AI breakdown response into GeneratedTicket structs.
    /// Exposed as internal for testing.
    func parseBreakdownResponse(_ content: String) throws -> [GeneratedTicket] {
        let jsonString = extractJSON(from: content)

        guard let jsonData = jsonString.data(using: .utf8) else {
            throw AIServiceError.parsingFailed("Could not convert response to data")
        }

        let decoded: AITicketBreakdownResponse
        do {
            decoded = try JSONDecoder().decode(AITicketBreakdownResponse.self, from: jsonData)
        } catch {
            throw AIServiceError.parsingFailed("JSON decode error: \(error.localizedDescription)")
        }

        return decoded.tickets.map { item in
            GeneratedTicket(
                title: item.title,
                description: item.description,
                priority: parsePriority(item.priority),
                estimatedStoryPoints: normalizeStoryPoints(item.storyPoints),
                skillClassification: parseSkillProfile(item.skillClassification),
                suggestedDependencies: item.dependencies ?? []
            )
        }
    }

    /// Parses the AI re-evaluation response into a ReEvaluationResult.
    func parseReEvaluationResponse(_ content: String) throws -> ReEvaluationResult {
        let jsonString = extractJSON(from: content)

        guard let jsonData = jsonString.data(using: .utf8) else {
            throw AIServiceError.parsingFailed("Could not convert response to data")
        }

        let decoded: AIReEvaluationResponse
        do {
            decoded = try JSONDecoder().decode(AIReEvaluationResponse.self, from: jsonData)
        } catch {
            throw AIServiceError.parsingFailed("JSON decode error: \(error.localizedDescription)")
        }

        let newTickets = decoded.newTickets.map { item in
            GeneratedTicket(
                title: item.title,
                description: item.description,
                priority: parsePriority(item.priority),
                estimatedStoryPoints: normalizeStoryPoints(item.storyPoints),
                skillClassification: parseSkillProfile(item.skillClassification),
                suggestedDependencies: item.dependencies ?? []
            )
        }

        let changedTickets = decoded.changedTickets.map { item in
            (
                existingTitle: item.existingTitle,
                suggested: GeneratedTicket(
                    title: item.suggested.title,
                    description: item.suggested.description,
                    priority: parsePriority(item.suggested.priority),
                    estimatedStoryPoints: normalizeStoryPoints(item.suggested.storyPoints),
                    skillClassification: parseSkillProfile(item.suggested.skillClassification),
                    suggestedDependencies: item.suggested.dependencies ?? []
                )
            )
        }

        return ReEvaluationResult(
            newTickets: newTickets,
            changedTickets: changedTickets,
            removedTicketTitles: decoded.removedTickets,
            unchangedTicketTitles: decoded.unchangedTickets
        )
    }

    /// Extracts JSON from a response that may contain markdown code fences.
    private func extractJSON(from content: String) -> String {
        let trimmed = content.trimmingCharacters(in: .whitespacesAndNewlines)

        // Check for markdown code fences
        if trimmed.hasPrefix("```") {
            let lines = trimmed.components(separatedBy: "\n")
            var jsonLines: [String] = []
            var insideBlock = false

            for line in lines {
                if line.hasPrefix("```") && !insideBlock {
                    insideBlock = true
                    continue
                } else if line.hasPrefix("```") && insideBlock {
                    break
                } else if insideBlock {
                    jsonLines.append(line)
                }
            }

            return jsonLines.joined(separator: "\n")
        }

        return trimmed
    }

    /// Parses a priority string into a TicketPriority enum value.
    private func parsePriority(_ value: String) -> TicketPriority {
        switch value.lowercased() {
        case "critical": return .critical
        case "high": return .high
        case "medium": return .medium
        case "low": return .low
        default: return .medium
        }
    }

    /// Parses a skill classification string into a SkillProfile enum value.
    private func parseSkillProfile(_ value: String) -> SkillProfile {
        switch value.lowercased() {
        case "beheavy", "be_heavy", "backend": return .beHeavy
        case "feheavy", "fe_heavy", "frontend": return .feHeavy
        case "fullstack", "full_stack": return .fullstack
        default: return .fullstack
        }
    }

    /// Normalizes story points to the nearest Fibonacci value.
    private func normalizeStoryPoints(_ value: Int) -> Int {
        let fibonacci = AppConstants.fibonacciSequence
        if fibonacci.contains(value) {
            return value
        }
        // Find the nearest Fibonacci number
        return fibonacci.min(by: { abs($0 - value) < abs($1 - value) }) ?? 3
    }
}
